{% set name = "ki18n" %}
{% set version = "5.75.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/ki18n-{{ version }}.tar.xz
  sha256: 71f22a4ef4a9e750a1813c9fe37b552d9e053e6e2249079b5908d078160130d3

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('ki18n', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
  host:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5I18n.so

about:
  home: https://api.kde.org/frameworks/ki18n/html/index.html
  license: BSD-3-Clause AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_file: 
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: KDE Gettext-based UI text internationalization
  description: |
    KI18n provides functionality for internationalizing user interface text in applications,
    based on the GNU Gettext translation system. It wraps the standard Gettext functionality,
    so that the programmers and translators can use the familiar Gettext tools and workflows.

    KI18n provides additional functionality as well, for both programmers and translators,
    which can help to achieve a higher overall quality of source and translated text.
    This includes argument capturing, customizable markup, and translation scripting.
  dev_url: https://cgit.kde.org/ki18n.git/tree

extra:
  recipe-maintainers:
    - scopatz
