travis:
  secure:
    BINSTAR_TOKEN: yam0dVaSdlEu8JsAwA5YhBXxIwVFIBSe+4Vd/6ttyxyLWP/6T3Mz9tuu3Z84XF2OSjsAoWAYAR3+1FpZlXvhKLZQcHumEmLId1xh/CDQcMwg2IfUYczyrKxI5uPMtweMVBP2DDKAm8mx3qmN8Otwkdj70K7o7oqosS3Khe0OC2A/uT/vzACodKfCW7a1jE+py0UoOOCSSNnkwSUvO8MUHyQxaeS9rwm9UbzxxKQBon8a0bBtO6OUCTUZyHn0s5opQFdntWMZ2w6fCL9S9rQ7f6KcEnOvu5NA4TfKuIOuNdPxsL4JOeUCvl9du+qaJd1e+lhi1uW+O+cw/kcAd/OFa3S7qWpvwFIK3rFgyna80GVuwsgLtIKRX/Y0DhyL0ZetOE926ahrEX9cxvRhcKnCU0z3bb4BmWRlujRIrTApH1jc3Q5G3/aMR5yv2CmFw5+JbE3WccSILyMh4NuBNK/F8d+Suuf0X8K8M90qBfcO/cRtM+P0e1q4P90N9qMl/NraeKEb3uY4h1I2wRhmdTgwsW9TVLgFIyn8UYLJkKTPE6kvVR82QPrpBFfTv/XSiQU43a99ylgiuEDoHQ37G+/0Tz/+WOkbhel3BRoxDpJCeto8ICOQ0mJcacXdBWlO8GiMW9dC+GZU2PpMYGM4tQOJwBlz6jZxk/htG2FL5b71s8A=
conda_forge_output_validation: true
bot:
  check_solvable: True
